name: Deploy documentation

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


permissions:
  contents: read
  pull-requests: write

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    name: Deploy API documentations on Bump
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: ./.github/scripts/deploy-all.sh
        env:
          AMADEUS_BUMP_TOKEN: ${{ secrets.AMADEUS_BUMP_TOKEN }}
          CLEVER_CLOUD_BUMP_TOKEN: ${{ secrets.CLEVER_CLOUD_BUMP_TOKEN }}
          EXAMPLES_BUMP_TOKEN: ${{ secrets.EXAMPLES_BUMP_TOKEN }}
          INTERCOM_BUMP_TOKEN: ${{ secrets.INTERCOM_BUMP_TOKEN }}
          MY_TRAIN_COMPANY_BUMP_TOKEN: ${{ secrets.MY_TRAIN_COMPANY_BUMP_TOKEN }}
          SCALEWAY_DEVELOPERS_BUMP_TOKEN: ${{ secrets.SCALEWAY_DEVELOPERS_BUMP_TOKEN }}
          TWITTER_API_V2_BUMP_TOKEN: ${{ secrets.TWITTER_API_V2_BUMP_TOKEN }}
          ZBOS_MQTT_BUMP_TOKEN: ${{ secrets.ZBOS_MQTT_BUMP_TOKEN }}
          PAYFIT_PARTNER_API_BUMP_TOKEN: ${{ secrets.PAYFIT_PARTNER_API_BUMP_TOKEN }}
          BUMP_HOST: ${{ secrets.BUMP_HOST }}
          GREENLY_BUMP_TOKEN: ${{ secrets.GREENLY_BUMP_TOKEN }}
          PIPEDRIVE_BUMP_TOKEN:  ${{ secrets.PIPEDRIVE_BUMP_TOKEN }}

  api-diff:
    if: ${{ github.event_name == 'pull_request' }}
    name: Check API diff on Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Debug repo variables
        run: echo "$BUMP_HOST"
        env:
          BUMP_HOST: ${{secrets.BUMP_HOST}}
      - name: Comment pull request with API diff
        uses: bump-sh/github-action@v1
        with:
          file: apis/greenly-openapi-source.json
          command: diff
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BUMP_HOST: ${{secrets.BUMP_HOST}}
