name: Deploy documentation

on:
  push:
    branches:
      - main

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    name: Deploy API documentations on Bump
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: ./.github/scripts/deploy-all.sh
        env:
          ORGANIZATION_DEMO_BUMP_TOKEN: ${{ secrets.ORGANIZATION_DEMO_BUMP_TOKEN }}

  deploy-workflows:
    runs-on: ubuntu-latest
    name: Deploy Workflows on Bump
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Deploy Weather workflow document
        uses: bump-sh/github-action@v1
        with:
          mcp_server: "cdb8573a-fd90-461a-a869-a6166a542592"
          token: ${{secrets.ORGANIZATION_DEMO_BUMP_TOKEN}}
          file: workflows/weather.yml
      - name: Deploy Wikimedia workflow document
        uses: bump-sh/github-action@v1
        with:
          mcp_server: "d1a6ad45-ca49-4c20-9440-f273988abba5"
          token: ${{secrets.ORGANIZATION_DEMO_BUMP_TOKEN}}
          file: workflows/wikimedia.json
